spring.application.name=auth-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db?currentSchema=public
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

jwt.secret=${JWT_SECRET:dev-only-secret-key-change-in-production-32bytes-min}
jwt.expiration-ms=3600000
